# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Enterprise Reference Data Service

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /categories:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets a summary list of all published reference data `categories`. Pagination is supported within this operation.
        
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in path and is required
        -
          name: fields
          in: query
          description: A qualifier used to define the fields to be returned in the response.
          required: false
          type: string
        -
          name: limit
          in: query
          description: a qualifier used to define the maximum number of records to be returned in the response. Used for pagination.
          required: false
          type: number
          format: integer
        -
          name: offset
          in: query
          description: a qualifier used to define the number of records to skip before returning data in the response. Used for pagination.
          required: false
          type: number
          format: integer
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCategories
            type: array
            items:
              $ref: '#/definitions/CategorySummary'
        204:
          description: No data available
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCategories
            type: array
            items:
              $ref: '#/definitions/CategorySummary'
        # Client Errors
        400:
          description: Bad Request
          schema:
            type: object          
            properties:
              status:
                type: string
                enum:
                  - fail
              data:
                $ref: '#/definitions/ErrorModel'
        # Server Errors
        500:
          description: Internal Server Error
          schema:
            type: object          
            properties:
              status:                         #error
                type: string
                enum:
                  - error
              data:
                $ref: '#/definitions/ErrorModel'
  # This is a path endpoint. Change it.
  /categories/{categoryName}/{categoryVersion}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets all details of the reference data `Category` including but not limited to name, version, description and all codes.
        Required path params of **categoryName** and **categoryVersion** determines the reference data `Category` record to be returned.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in path and is required
        -
          name: categoryName
          in: path
          description: Name of enterprise reference data Category
          required: true
          type: string
          format: string
        -
          name: categoryVersion
          in: path
          description: Qualifies the major version of reference data category. Default for all requests is 'v1'.
          required: true
          type: string
          format: string
        #-
        #  name: fields
        #  in: query
        #  description: A qualifier used to define the fields to be returned in the response.
        #  required: false
        #  type: string
        #-
        #  name: limit
        #  in: query
        #  description: a qualifier used to define the maximum number of records to be returned in the response. Used for pagination.
        #  required: false
        #  type: number
        #  format: integer
        #-
        #  name: offset
        #  in: query
        #  description: a qualifier used to define the number of records to skip before returning data in the response. Used for pagination.
        #  required: false
        #  type: number
        #  format: integer
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCategories
            type: array
            items:
              $ref: '#/definitions/CategoryDetails'
        204:
          description: No data available
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCategories
            type: array
            items:
              $ref: '#/definitions/CategoryDetails'
        # Client Errors
        400:
          description: Bad Request
          schema:
            type: object          
            properties:
              status:
                type: string
                enum:
                  - fail
              data:
                $ref: '#/definitions/ErrorModel'
        # Server Errors
        500:
          description: Internal Server Error
          schema:
            type: object          
            properties:
              status:                         #error
                type: string
                enum:
                  - error
              data:
                $ref: '#/definitions/ErrorModel'
  # This is a path endpoint. Change it.
  /categories/{categoryName}/{categoryVersion}/codes:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets all canonical and system codes that are part of the reference data `Category`. 
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in path and is required
        -
          name: categoryName
          in: path
          description: Name of enterprise reference data Category
          required: true
          type: string
          format: string
        -
          name: categoryVersion
          in: path
          description: Qualifies the major version of reference data category. 
          required: true
          type: string
          format: string
        -
          name: codeType
          in: query
          description: Qualifies if canonical or system codes are required. Example 'canonical' or 'system1Code' for the System1. Pagination is supported within this operation.
          required: false
          type: string
          format: string
        -
          name: fields
          in: query
          description: A qualifier used to define the fields to be returned in the response.
          required: false
          type: string
        -
          name: limit
          in: query
          description: a qualifier used to define the maximum number of records to be returned in the response. Used for pagination.
          required: false
          type: number
          format: integer
        -
          name: offset
          in: query
          description: a qualifier used to define the number of records to skip before returning data in the response. Used for pagination.
          required: false
          type: number
          format: integer
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCategoryCodes
            type: array
            items:
              $ref: '#/definitions/Codes' 
        # Client Errors
        400:
          description: Bad Request
          schema:
            type: object          
            properties:
              status:
                type: string
                enum:
                  - fail
              data:
                $ref: '#/definitions/ErrorModel'
        # Server Errors
        500:
          description: Internal Server Error
          schema:
            type: object          
            properties:
              status:                         #error
                type: string
                enum:
                  - error
              data:
                $ref: '#/definitions/ErrorModel'
  # This is a path endpoint. Change it.
  /categories/{categoryName}/{categoryVersion}/codes/{code}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets the code record for the given canonical **code**. If **not** a canonical code value then the **sourceCodeTypeQualifer** query param is required as it qualifies which syste the code belongs to. Pagination is supported within this operation.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: categoryName
          in: path
          description: The name of the reference data category
          required: true
          type: number
          format: string
        -
          name: categoryVersion
          in: path
          description: Qualifies the major version of reference data category
          required: true
          type: string
          format: string
        -
          name: code
          in: path
          description: Qualifies the code value of the document
          required: true
          type: number
          format: string
        -
          name: sourceCodeTypeQualifier
          in: query
          description: Qualifies if the code is the canonical or a system code. For system should use Application Inventory ID of the system without '-' (hyphen). Example 'System1Code' to qualify that the code is the System1 system code. If not provided it is assumed the code is the canonical code
          required: false
          type: number
          format: string
        -
          name: fields
          in: query
          description: A qualifier used to define the fields to be returned in the response.
          required: false
          type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCodes
            type: array
            items:
              $ref: '#/definitions/Codes'
        # Client Errors
        400:
          description: Bad Request
          schema:
            type: object          
            properties:
              status:
                type: string
                enum:
                  - fail
              data:
                $ref: '#/definitions/ErrorModel'
        # Server Errors
        500:
          description: Internal Server Error
          schema:
            type: object          
            properties:
              status:                         #error
                type: string
                enum:
                  - error
              data:
                $ref: '#/definitions/ErrorModel'
definitions:
  Codes:
    discriminator: canonicalCode
    required:
      - category
      - version # required for inheritance to work
      - canonicalCode
    properties:
      category: 
        type: string
        description: The name of the reference data category
      version:
        type: string
        description: The major version number of the category prefixed by the letter v
      canonicalCode:
        type: string
        description: The canonical code value
      description:
        type: string
        description: The description of the canonical code value
      system1Code:
        type: string
        description: The code value of System 1
      system2Code:
        type: string
        description: The code value of System 2
        
  CategorySummary:
    discriminator: canonicalCode
    required:
      - category
      - version # required for inheritance to work
    properties:
      category: 
        type: string
        description: The name of the reference data category
      version:
        type: string
        description: The major version number of the category prefixed by the letter 'v'
      description:
        type: string
        description: The description of the reference data category

  CategoryDetails:
    discriminator: canonicalCode
    required:
      - category
      - version # required for inheritance to work
    properties:
      category: 
        type: string
        description: The name of the reference data category
      version:
        type: string
        description: The major version number of the category prefixed by the letter 'v'
      description:
        type: string
        description: The description of the reference data category
      parentCategory:
        type: string
      codes:
        type: array
        description: The complete list of canonical and system codes that are part of the reference data category
        items:
          $ref: '#/definitions/Codes'
  #The common error object        
  ErrorModel:
    description: Represents the error Model, returned in case of error conditions
    type: object
    properties:
      errorList:
        type: array
        items:
          $ref: '#/definitions/Error'

  # Individual Error Object
  Error:
    description:  Represent an invidual error.
    type: object
    properties:
      code:
        description:  Error Code.
        type: integer
        format: int32
      message:
        description:  Error Message
        type: string
      fields:
        description: Comma seperated list of fields, which caused the error condition.
        type: string